name: pathans-lab

on:
 push:
   branches: main

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps:
     - name: kitkat
       if: ${{github.event_name == 'push'}}
       run: |
         echo "this is kitkat"
