name: pathans-lab
run-name: our workflow ${{inputs.name}}
on:
 workflow_dispatch: 
    inputs:
      name:
        type: string
        default: conditional

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps:
     - name: kitkat
       if: ${{github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
       run: |
         echo "this is kitkat-${{github.event_name}}"

