name: pathans-lab

on:
 workflow_dispatch: 

jobs:
  job1:
   runs-on: ubuntu-latest
   
   steps:
     - name: kitkat
       if: ${{github.event_name == 'push'}}
       run: |
         echo "this is kitkat-${{github.event_name}}"
         
