name: pathans-lab

on:
 push:
   branches: main

jobs:
  job1:
   runs-on: ubuntu-latest

   steps:
    - name: yamdooing
      id: pv
      run: echo "name=basha" >> "$GITHUB_OUTPUT"
    
    - name: yamlfile
      run: echo "${{steps.pv.outputs.name}}"