name: pathans-lab

on:
 push:
   branches: main

jobs:
  job1:
   runs-on: ubuntu-latest

   steps:
    - name: yamdooing
      id: pv
      run: |
        echo "name=basha" >> "$GITHUB_OUTPUT"
        echo "job=devops" >> "$GITHUB_OUTPUT"
        echo "$GITHUB_OUTPUT"
    
    - name: yamlfile
      id: hi
      run: |
        echo "friend=akhil" >> "$GITHUB_OUTPUT"
        echo "name is ${{steps.pv.outputs.name}}"
        echo "job is ${{steps.pv.outputs.job}}"
        echo "$GITHUB_OUTPUT"


    